### ISSUE TITLE
Can't start Archetype

### ISSUE THREAD

**Issue by nthieberger** [kcl-ddh/digipal#47]
I get this and then nothing. Having installed Kitematic on macbook pro, started archetype, but then  ...
------------------------------
STARTING CONTAINER...
 * Starting PostgreSQL 9.5 database server
   ...done.
WARNING: local_settings.py not found
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 191, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 53, in ensure_schema
    editor.create_model(self.Migration)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: no schema has been selected to create in
LINE 1: CREATE TABLE "django_migrations" ("id" serial NOT NULL PRIMA...
                     ^
2020-06-26T06:47:38.934393129Z 
WARNING: local_settings.py not found
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 191, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 53, in ensure_schema
    editor.create_model(self.Migration)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: no schema has been selected to create in
LINE 1: CREATE TABLE "django_migrations" ("id" serial NOT NULL PRIMA...
                     ^
2020-06-26T06:47:39.950094365Z 
WARNING: local_settings.py not found
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 190, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/digipal/digipal/management/commands/dpsearch.py", line 11, in <module>
    from digipal.views.faceted_search.search_indexer import SearchIndexer
  File "/home/digipal/digipal/views/faceted_search/search_indexer.py", line 4, in <module>
    from digipal.views.faceted_search import faceted_search
  File "/home/digipal/digipal/views/faceted_search/faceted_search.py", line 5, in <module>
    from digipal.forms import SearchPageForm
  File "/home/digipal/digipal/forms.py", line 44, in <module>
    class ImageAnnotationForm(forms.Form):
  File "/home/digipal/digipal/forms.py", line 47, in ImageAnnotationForm
    if status_list:
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 170, in __nonzero__
    return type(self).__bool__(self)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 166, in __bool__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "digipal_status" does not exist
LINE 1: ...atus"."created", "digipal_status"."modified" FROM "digipal_s...
                                                             ^
2020-06-26T06:48:18.121449590Z 
WARNING: local_settings.py not found
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 190, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/digipal/digipal/management/commands/dpsearch.py", line 11, in <module>
    from digipal.views.faceted_search.search_indexer import SearchIndexer
  File "/home/digipal/digipal/views/faceted_search/search_indexer.py", line 4, in <module>
    from digipal.views.faceted_search import faceted_search
  File "/home/digipal/digipal/views/faceted_search/faceted_search.py", line 5, in <module>
    from digipal.forms import SearchPageForm
  File "/home/digipal/digipal/forms.py", line 44, in <module>
    class ImageAnnotationForm(forms.Form):
  File "/home/digipal/digipal/forms.py", line 47, in ImageAnnotationForm
    if status_list:
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 170, in __nonzero__
    return type(self).__bool__(self)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 166, in __bool__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "digipal_status" does not exist
LINE 1: ...atus"."created", "digipal_status"."modified" FROM "digipal_s...
                                                             ^
2020-06-26T06:48:38.874945989Z 
 * Stopping PostgreSQL 9.5 database server
   ...done.
waiting for site... (1)
2020-06-26 06:49:00,891 CRIT Supervisor running as root (no user in config file)
2020-06-26 06:49:00,896 INFO supervisord started with pid 146
waiting for site... (2)
2020-06-26 06:49:01,901 INFO spawned: 'pgsql' with pid 153
2020-06-26 06:49:01,903 INFO spawned: 'iipsrv' with pid 154
2020-06-26 06:49:01,906 INFO spawned: 'django' with pid 155
2020-06-26 06:49:01,908 INFO spawned: 'nginx' with pid 156
waiting for site... (3)
2020-06-26 06:49:03,867 INFO success: pgsql entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-06-26 06:49:03,867 INFO success: iipsrv entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-06-26 06:49:03,868 INFO success: django entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-06-26 06:49:03,868 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
waiting for site... (4)
waiting for site... (5)
waiting for site... (6)
waiting for site... (7)
waiting for site... (8)
waiting for site... (9)
waiting for site... (10)
waiting for site... (11)
waiting for site... (12)
waiting for site... (13)
waiting for site... (14)
waiting for site... (15)
waiting for site... (16)
waiting for site... (17)
waiting for site... (18)
waiting for site... (19)
waiting for site... (20)
waiting for site... (21)
waiting for site... (22)
waiting for site... (23)
waiting for site... (24)
waiting for site... (25)
waiting for site... (26)
waiting for site... (27)
waiting for site... (28)
waiting for site... (29)
waiting for site... (30)
waiting for site... (31)
waiting for site... (32)
waiting for site... (33)
waiting for site... (34)
waiting for site... (35)
waiting for site... (36)
waiting for site... (37)
waiting for site... (38)
waiting for site... (39)
waiting for site... (40)
waiting for site... (41)
waiting for site... (42)
waiting for site... (43)
waiting for site... (44)
waiting for site... (45)
waiting for site... (46)
waiting for site... (47)
waiting for site... (48)
waiting for site... (49)
waiting for site... (50)
waiting for site... (51)
waiting for site... (52)
waiting for site... (53)
waiting for site... (54)
waiting for site... (55)
waiting for site... (56)
waiting for site... (57)
waiting for site... (58)
waiting for site... (59)
waiting for site... (60)
waiting for site... (61)
waiting for site... (62)
waiting for site... (63)
waiting for site... (64)
waiting for site... (65)
waiting for site... (66)
waiting for site... (67)
waiting for site... (68)
waiting for site... (69)
waiting for site... (70)
waiting for site... (71)
waiting for site... (72)
waiting for site... (73)
waiting for site... (74)
waiting for site... (75)
waiting for site... (76)
waiting for site... (77)
waiting for site... (78)
waiting for site... (79)
waiting for site... (80)
waiting for site... (81)
waiting for site... (82)
waiting for site... (83)
waiting for site... (84)
waiting for site... (85)
waiting for site... (86)
waiting for site... (87)
waiting for site... (88)
waiting for site... (89)
waiting for site... (90)
waiting for site... (91)
waiting for site... (92)
waiting for site... (93)
waiting for site... (94)
waiting for site... (95)
waiting for site... (96)
waiting for site... (97)
waiting for site... (98)
waiting for site... (99)
waiting for site... (100)
waiting for site... (101)
waiting for site... (102)
waiting for site... (103)
waiting for site... (104)
waiting for site... (105)
waiting for site... (106)
waiting for site... (107)
waiting for site... (108)
waiting for site... (109)
waiting for site... (110)
waiting for site... (111)
waiting for site... (112)
waiting for site... (113)
waiting for site... (114)
waiting for site... (115)
waiting for site... (116)
waiting for site... (117)
waiting for site... (118)
waiting for site... (119)
waiting for site... (120)
waiting for site... (121)
waiting for site... (122)
waiting for site... (123)
waiting for site... (124)
waiting for site... (125)
waiting for site... (126)
waiting for site... (127)
waiting for site... (128)
waiting for site... (129)
waiting for site... (130)
waiting for site... (131)
waiting for site... (132)
waiting for site... (133)
waiting for site... (134)
waiting for site... (135)
waiting for site... (136)
waiting for site... (137)
waiting for site... (138)
waiting for site... (139)
waiting for site... (140)
waiting for site... (141)
waiting for site... (142)
waiting for site... (143)
waiting for site... (144)
 * Starting PostgreSQL 9.5 database server
   ...done.
WARNING: local_settings.py not found
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 191, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 53, in ensure_schema
    editor.create_model(self.Migration)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: no schema has been selected to create in
LINE 1: CREATE TABLE "django_migrations" ("id" serial NOT NULL PRIMA...
                     ^
2020-06-26T06:52:12.725852319Z 
WARNING: local_settings.py not found
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 191, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 53, in ensure_schema
    editor.create_model(self.Migration)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: no schema has been selected to create in
LINE 1: CREATE TABLE "django_migrations" ("id" serial NOT NULL PRIMA...
                     ^
2020-06-26T06:52:13.747660970Z 
WARNING: local_settings.py not found
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 190, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/digipal/digipal/management/commands/dpsearch.py", line 11, in <module>
    from digipal.views.faceted_search.search_indexer import SearchIndexer
  File "/home/digipal/digipal/views/faceted_search/search_indexer.py", line 4, in <module>
    from digipal.views.faceted_search import faceted_search
  File "/home/digipal/digipal/views/faceted_search/faceted_search.py", line 5, in <module>
    from digipal.forms import SearchPageForm
  File "/home/digipal/digipal/forms.py", line 44, in <module>
    class ImageAnnotationForm(forms.Form):
  File "/home/digipal/digipal/forms.py", line 47, in ImageAnnotationForm
    if status_list:
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 170, in __nonzero__
    return type(self).__bool__(self)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 166, in __bool__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "digipal_status" does not exist
LINE 1: ...atus"."created", "digipal_status"."modified" FROM "digipal_s...
                                                             ^
2020-06-26T06:52:58.592213391Z 
WARNING: local_settings.py not found
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 190, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/digipal/digipal/management/commands/dpsearch.py", line 11, in <module>
    from digipal.views.faceted_search.search_indexer import SearchIndexer
  File "/home/digipal/digipal/views/faceted_search/search_indexer.py", line 4, in <module>
    from digipal.views.faceted_search import faceted_search
  File "/home/digipal/digipal/views/faceted_search/faceted_search.py", line 5, in <module>
    from digipal.forms import SearchPageForm
  File "/home/digipal/digipal/forms.py", line 44, in <module>
    class ImageAnnotationForm(forms.Form):
  File "/home/digipal/digipal/forms.py", line 47, in ImageAnnotationForm
    if status_list:
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 170, in __nonzero__
    return type(self).__bool__(self)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 166, in __bool__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "digipal_status" does not exist
LINE 1: ...atus"."created", "digipal_status"."modified" FROM "digipal_s...
                                                             ^
2020-06-26T06:53:23.572970762Z 
 * Stopping PostgreSQL 9.5 database server
   ...done.
waiting for site... (1)
2020-06-26 06:53:47,627 CRIT Supervisor running as root (no user in config file)
2020-06-26 06:53:47,631 INFO supervisord started with pid 151
waiting for site... (2)
2020-06-26 06:53:48,633 INFO spawned: 'pgsql' with pid 158
2020-06-26 06:53:48,635 INFO spawned: 'iipsrv' with pid 159
2020-06-26 06:53:48,638 INFO spawned: 'django' with pid 160
2020-06-26 06:53:48,640 INFO spawned: 'nginx' with pid 161
waiting for site... (3)
2020-06-26 06:53:50,624 INFO success: pgsql entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-06-26 06:53:50,624 INFO success: iipsrv entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-06-26 06:53:50,624 INFO success: django entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-06-26 06:53:50,624 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
waiting for site... (4)
waiting for site... (5)
waiting for site... (6)
waiting for site... (7)
waiting for site... (8)
waiting for site... (9)
waiting for site... (10)
waiting for site... (11)
waiting for site... (12)
waiting for site... (13)
waiting for site... (14)
waiting for site... (15)
waiting for site... (16)
waiting for site... (17)
waiting for site... (18)
waiting for site... (19)
waiting for site... (20)
waiting for site... (21)
waiting for site... (22)
waiting for site... (23)
waiting for site... (24)
waiting for site... (25)
waiting for site... (26)
waiting for site... (27)
waiting for site... (28)
waiting for site... (29)
waiting for site... (30)
waiting for site... (31)
waiting for site... (32)
waiting for site... (33)
waiting for site... (34)
waiting for site... (35)
waiting for site... (36)
waiting for site... (37)
waiting for site... (38)
waiting for site... (39)
waiting for site... (40)
waiting for site... (41)
waiting for site... (42)
waiting for site... (43)
waiting for site... (44)
waiting for site... (45)
waiting for site... (46)
waiting for site... (47)
waiting for site... (48)
waiting for site... (49)
waiting for site... (50)
waiting for site... (51)
waiting for site... (52)
waiting for site... (53)
waiting for site... (54)
waiting for site... (55)
waiting for site... (56)
waiting for site... (57)
waiting for site... (58)
waiting for site... (59)
waiting for site... (60)
waiting for site... (61)
waiting for site... (62)
waiting for site... (63)
waiting for site... (64)
waiting for site... (65)
waiting for site... (66)
waiting for site... (67)
waiting for site... (68)
waiting for site... (69)
waiting for site... (70)
waiting for site... (71)
waiting for site... (72)
waiting for site... (73)
waiting for site... (74)
waiting for site... (75)
waiting for site... (76)
waiting for site... (77)
waiting for site... (78)
waiting for site... (79)
waiting for site... (80)
waiting for site... (81)
waiting for site... (82)
waiting for site... (83)
waiting for site... (84)
waiting for site... (85)
waiting for site... (86)
waiting for site... (87)
waiting for site... (88)
waiting for site... (89)
waiting for site... (90)
waiting for site... (91)
waiting for site... (92)
waiting for site... (93)
waiting for site... (94)
waiting for site... (95)
waiting for site... (96)
waiting for site... (97)
waiting for site... (98)
waiting for site... (99)
waiting for site... (100)
waiting for site... (101)
waiting for site... (102)
waiting for site... (103)
waiting for site... (104)
waiting for site... (105)
waiting for site... (106)
waiting for site... (107)
waiting for site... (108)
waiting for site... (109)
waiting for site... (110)
waiting for site... (111)
waiting for site... (112)
waiting for site... (113)
waiting for site... (114)
waiting for site... (115)
waiting for site... (116)
waiting for site... (117)
waiting for site... (118)
waiting for site... (119)
waiting for site... (120)
waiting for site... (121)
waiting for site... (122)
waiting for site... (123)
waiting for site... (124)
waiting for site... (125)
waiting for site... (126)
waiting for site... (127)
waiting for site... (128)
waiting for site... (129)
waiting for site... (130)
waiting for site... (131)
waiting for site... (132)
waiting for site... (133)
waiting for site... (134)
waiting for site... (135)
waiting for site... (136)
waiting for site... (137)
waiting for site... (138)
waiting for site... (139)
waiting for site... (140)
waiting for site... (141)
waiting for site... (142)
waiting for site... (143)
waiting for site... (144)
waiting for site... (145)
waiting for site... (146)
waiting for site... (147)
waiting for site... (148)
waiting for site... (149)
waiting for site... (150)
waiting for site... (151)
waiting for site... (152)
waiting for site... (153)
waiting for site... (154)
waiting for site... (155)
waiting for site... (156)
waiting for site... (157)
waiting for site... (158)
waiting for site... (159)
waiting for site... (160)
waiting for site... (161)
waiting for site... (162)
waiting for site... (163)
waiting for site... (164)
waiting for site... (165)
waiting for site... (166)
waiting for site... (167)
waiting for site... (168)
waiting for site... (169)
waiting for site... (170)
waiting for site... (171)
waiting for site... (172)
waiting for site... (173)
waiting for site... (174)
waiting for site... (175)
waiting for site... (176)
waiting for site... (177)
waiting for site... (178)
waiting for site... (179)
waiting for site... (180)
waiting for site... (181)
waiting for site... (182)
waiting for site... (183)
waiting for site... (184)
waiting for site... (185)
waiting for site... (186)
waiting for site... (187)
waiting for site... (188)
waiting for site... (189)
waiting for site... (190)
waiting for site... (191)
waiting for site... (192)
waiting for site... (193)
waiting for site... (194)
waiting for site... (195)
waiting for site... (196)
waiting for site... (197)
waiting for site... (198)
waiting for site... (199)
waiting for site... (200)

**Comment by pastokes** [comment]
Thanks for raising this. It's hard to tell from here what's happened, but I have found once before with a new install on a Mac that for some reason the Postgres database wasn't created properly, and that may be the problem here too. The workaround was to create the digipal database and app_digipal user manually from the command line (following the settings in digipal/local_settings.template.py), then restarting the Django instance.

**Comment by e-sonego** [comment]
I cannot install Archetype properly. I installed Kitematic on Mac, when I run the command as described on the command line, I get "INSTALLED", but the container does not show up in Kitematik. If I search and create Archetype via the Kitematic interface, it tells me "no such image".
